// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MyDashboard.Model.Entities.Entities;

[Table("ErrorLog", Schema = "MD")]
public partial class ErrorLog
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Required]
    [StringLength(50)]
    public string LogLevel { get; set; }

    [Required]
    public string Message { get; set; }

    public string Exception { get; set; }

    [StringLength(100)]
    public string Source { get; set; }
}